"""Added the session column.

Revision ID: 130268845272
Revises: 27ba4bd69d9f
Create Date: 2012-10-28 07:22:00.892183

"""

# revision identifiers, used by Alembic.
revision = '130268845272'
down_revision = '27ba4bd69d9f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datapoints', sa.Column('session', sa.Unicode(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datapoints', 'session')
    ### end Alembic commands ###
